// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCULHNA6eYThW-c_N5TR5r5Eiv3nnCTPMk',
    appId: '1:1024388778503:web:4be0a295d6a25bea55b8a2',
    messagingSenderId: '1024388778503',
    projectId: 'quickmart-7fa3f',
    authDomain: 'quickmart-7fa3f.firebaseapp.com',
    storageBucket: 'quickmart-7fa3f.appspot.com',
    measurementId: 'G-ZS443NKGC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2WP5WoJQK7dvRHLfbOMkEoMTEtDeHzY0',
    appId: '1:1024388778503:android:b3b202e620a9409a55b8a2',
    messagingSenderId: '1024388778503',
    projectId: 'quickmart-7fa3f',
    storageBucket: 'quickmart-7fa3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9C-w2C8XA2cnyPLKDXTVFv7c4WE-MwHY',
    appId: '1:1024388778503:ios:5942d1209d1cb75655b8a2',
    messagingSenderId: '1024388778503',
    projectId: 'quickmart-7fa3f',
    storageBucket: 'quickmart-7fa3f.appspot.com',
    iosBundleId: 'com.example.ecommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9C-w2C8XA2cnyPLKDXTVFv7c4WE-MwHY',
    appId: '1:1024388778503:ios:5942d1209d1cb75655b8a2',
    messagingSenderId: '1024388778503',
    projectId: 'quickmart-7fa3f',
    storageBucket: 'quickmart-7fa3f.appspot.com',
    iosBundleId: 'com.example.ecommerceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCULHNA6eYThW-c_N5TR5r5Eiv3nnCTPMk',
    appId: '1:1024388778503:web:aa3a0326cde49ab755b8a2',
    messagingSenderId: '1024388778503',
    projectId: 'quickmart-7fa3f',
    authDomain: 'quickmart-7fa3f.firebaseapp.com',
    storageBucket: 'quickmart-7fa3f.appspot.com',
    measurementId: 'G-G1HE1J4X25',
  );
}
